python3 run.py --gpu_ids 0 \
--path_to_train_data ../dataset/nf_prize_dataset/Netflix/N3M_TRAIN \
--path_to_eval_data ../dataset/nf_prize_dataset/Netflix/N3M_VALID \
--hidden_layers 512,512,1024 \
--non_linearity_type selu \
--batch_size 128 \
--logdir model_save \
--drop_prob 0.8 \
--optimizer momentum \
--lr 0.005 \
--weight_decay 0 \
--aug_step 1 \
--noise_prob 0 \
--num_epochs 200 \
--summary_frequency 1000